# CoinManager created by JoshiZockt_
Lang:
  Coin: 'Coin'
  Coins: 'Coins'
  Prefix: '&8[&e&l%coins%&8] &7'
  CoinsCommand: 'Your %coins%: &e%playerCoins%'
  OtherCoinsCommand: '%player%`s %coins%: &e%playerCoins%'

Config:
  Storage:
    # FILE
    # MYSQL
    Type: FILE

    MYSQL:
      Host: ''
      User: ''
      Password: ''
      Database: ''
      Port: 3306
      Table: 'coins'

    FILE:
      Filename: 'coins.yml'

  Lang:
    SendMessages: true
    SendMessageSound: true
    MessageSound: LEVEL_UP

  Coins:
    DefaultCoins: 1000